[tool.poetry]
name = "copulapairtrading"
version = "0.1.0"
description = ""
authors = ["Samay Panwar <samaybhuvi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pre-commit = "^3.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
